vnet = "NRHL-WestUS-1"
subnet = "QA"
location = "West US"
privateipaddress = ""
VM_name = "terraform"
VM_size = "Standard_DS1_v2"
admin_username = "nrhladmin"
admin_password = "XXXXXXXX"
vnet_resource_group_name="EnterpriseApps-Network"
VM_resource_group_name = "EnterpriseApps-Platform-PoC"
domain_user_name = "hautelook//Gangahdar.Reddy"
domain_user_password="XXXXX"

